async function loadRosters(){try{let t=await fetch('rosters.html',{cache:'no-store'}).then(r=>r.text()),m=t.match(/const D=(\{[\s\S]*?\})\s*;let cat=/);if(m)D=Function('return ('+m[1]+')')()}catch(e){}applyOfficialOverrides();renderTeams();renderHome()}
function groupName(team){return groups.A.includes(team)?'المجموعة A':groups.B.includes(team)?'المجموعة B':groups.C.includes(team)?'المجموعة C':'المجموعة غير مسجلة'}
function card(m,compact=false){return `<button class="card match-card ${compact?'compact':''}" onclick='openMatch(${JSON.stringify(m).replaceAll("'","&#39;")})'><div class="match-meta"><span>${m.stage}${m.group?' · المجموعة '+m.group:''}</span><span class="status"><i></i> لم تبدأ</span></div><div class="match-row"><div class="team"><img src="${logo(m.a)}"><b>${m.a}</b></div><div class="vs">VS</div><div class="team"><img src="${logo(m.b)}"><b>${m.b}</b></div></div><div class="match-footer"><span>${fmtDate(m.date)}</span><span>${m.time}</span></div></button>`}
function nextSenior(){let now=new Date();return seniorMatches.find(m=>dt(m)>now)||seniorMatches[0]}
function renderHome(){let n=nextSenior();nextMatch.innerHTML=card(n);let el=nextMatch.querySelector('.match-footer');if(el){let c=document.createElement('span');c.className='countdown';el.appendChild(c);const tick=()=>{let x=dt(n)-new Date();if(x<=0){c.textContent='موعد المباراة';return}let d=Math.floor(x/864e5),h=Math.floor(x%864e5/36e5),mi=Math.floor(x%36e5/6e4);c.textContent=`بعد ${d}ي ${h}س ${mi}د`};tick();setInterval(tick,60000)}upcoming.innerHTML=seniorMatches.filter(m=>dt(m)>=dt(n)).slice(0,4).map(m=>card(m,true)).join('');renderFavorite();renderNews()}
function renderMatches(cat='الكبار'){let a=cat==='الكبار'?seniorMatches:cat==='الوسط'?middleMatches:smallMatches;matchesList.innerHTML=a.map(m=>`<div class="schedule-day">${fmtDate(m.date)}</div>${card(m)}`).join('')}
document.querySelectorAll('[data-matchcat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-matchcat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMatches(b.dataset.matchcat)});
function renderGroups(){groups.innerHTML=Object.entries(groups).map(([g,ts])=>`<div class="card group-card"><small>المجموعة ${g}</small>${ts.map(n=>`<div class="tteam"><img src="${logo(n)}"><b>${n}</b></div>`).join('')}</div>`).join('')}
function renderStandings(){standings.innerHTML=Object.entries(groups).map(([g,ts])=>`<div class="section"><div class="head"><h2>المجموعة ${g}</h2></div><div class="standings"><table class="table"><thead><tr><th>الفريق</th><th>لعب</th><th>ف</th><th>ت</th><th>خ</th><th>له</th><th>عليه</th><th>+/-</th><th>ن</th></tr></thead><tbody>${ts.map(n=>`<tr><td><div class="tteam"><img src="${logo(n)}"><b>${n}</b></div></td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>`).join('')}</tbody></table></div></div>`).join('')}
function renderBracket(){bracket.innerHTML=`<div class="bracket"><div class="card"><small style="color:var(--gold)">نصف النهائي 1 · 14 سبتمبر · 17:30</small><h3>متصدر المجموعة A × متصدر المجموعة C</h3></div><div class="card"><small style="color:var(--gold)">نصف النهائي 2 · 15 سبتمبر · 17:30</small><h3>وصيف المجموعة A × متصدر المجموعة B</h3></div><div class="card"><small style="color:var(--gold)">النهائي · 20 سبتمبر · 17:30</small><h3>الفائز من نصف النهائي الأول × الفائز من نصف النهائي الثاني</h3></div></div>`}
function renderReferees(){referees.innerHTML=`<div class="ref-grid">${Object.entries(refereeAssignments).map(([cat,r])=>`<div class="card ref-card"><h3>طاقم حكام ${cat}</h3><div class="ref-role"><span>الحكم الرئيسي</span><b>${r.main}</b></div><div class="ref-role"><span>الحكم المساعد</span><b>${r.assistant}</b></div></div>`).join('')}</div>`}
function showTournamentTab(id,btn){document.querySelectorAll('.tourtab').forEach(x=>x.classList.add('hidden'));document.getElementById('tour-'+id).classList.remove('hidden');document.querySelectorAll('#tournament .tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(id==='standings')renderStandings();if(id==='bracket')renderBracket();if(id==='refs')renderReferees()}
function renderTeams(){let q=(teamSearch.value||'').trim().toLowerCase(),c=document.querySelector('[data-teamcat].active')?.dataset.teamcat||'الكل',rows=[];Object.entries(D).forEach(([cat,ts])=>{if(c!=='الكل'&&c!==cat)return;Object.entries(ts).forEach(([n,ps])=>{if(!q||n.toLowerCase().includes(q)||ps.some(p=>pname(p).toLowerCase().includes(q)))rows.push({cat,n,ps})})});teamGrid.innerHTML=rows.map(x=>`<button class="card teamcard" onclick="openTeam('${x.n.replaceAll("'","\\'")}','${x.cat}')"><img src="${logo(x.n)}"><h3>${x.n}</h3><p>${x.cat} · ${x.ps.length} لاعب</p></button>`).join('')||'<div class="card empty" style="grid-column:1/-1"><b>لا توجد نتائج</b><span>جرّب بحثًا آخر.</span></div>'}
document.querySelectorAll('[data-teamcat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-teamcat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTeams()});teamSearch.oninput=renderTeams;
function showSheet(h){sheetPanel.innerHTML=h;sheet.classList.add('show')} function closeSheet(){sheet.classList.remove('show')} function initial(n){return (n.trim()[0]||'؟')}