(() => {
  'use strict';
  const SDK='https://cdn.jsdelivr.net/npm/livekit-client@2.15.6/dist/livekit-client.umd.min.js';let sdkPromise;const rooms=new WeakMap();
  const load=()=>window.LivekitClient?Promise.resolve(window.LivekitClient):(sdkPromise||(sdkPromise=new Promise((ok,no)=>{const s=document.createElement('script');s.src=SDK;s.async=true;s.crossOrigin='anonymous';s.onload=()=>window.LivekitClient?ok(window.LivekitClient):no(new Error('LiveKit unavailable'));s.onerror=()=>no(new Error('LiveKit unavailable'));document.head.appendChild(s)})));
  const matchId=input=>{const raw=String(input.url||'');const m=raw.match(/match-([A-Za-z0-9-]+)/);return m?.[1]||String(input.matchId||'').replace(/[^A-Za-z0-9-]/g,'')};
  async function render(container,input={}){
    if(!container)return false;if(String(input.type||'').toLowerCase()!=='livekit')return false;
    const enabled=input.enabled===true||input.enabled==='true',status=String(input.status||'').toLowerCase();if(!enabled||status!=='live'){container.hidden=true;return true}
    const id=matchId(input);if(!id){container.hidden=true;return true}container.hidden=false;const stage=container.querySelector('[data-stream-stage]')||container;stage.innerHTML='<div class="stream-unavailable" role="status"><p>جارٍ الاتصال بالبث المباشر…</p></div>';
    try{const LK=await load();const r=await fetch('/api/livekit-token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({room:`match-${id}`,role:'viewer'})});const auth=await r.json();if(!r.ok)throw new Error(auth.error||'token');const room=new LK.Room({adaptiveStream:true,dynacast:true});rooms.set(container,room);const media=document.createElement('div');media.style.cssText='width:100%;min-height:220px;background:#000;display:grid;place-items:center';stage.replaceChildren(media);const attach=track=>{const el=track.attach();el.autoplay=true;el.playsInline=true;el.style.cssText='width:100%;height:auto;max-height:75vh;object-fit:contain;background:#000';media.appendChild(el)};room.on(LK.RoomEvent.TrackSubscribed,(track)=>attach(track));room.on(LK.RoomEvent.Disconnected,()=>{if(document.contains(container))stage.innerHTML='<div class="stream-unavailable"><p>انتهى البث المباشر.</p></div>'});await room.connect(auth.url,auth.token);room.remoteParticipants.forEach(p=>p.trackPublications.forEach(pub=>{if(pub.track)attach(pub.track)}));container.classList.add('stream-ready');return true}catch(e){console.error('LiveKit viewer',e);stage.innerHTML='<div class="stream-unavailable" role="status"><p>تعذر الاتصال بالبث المباشر حاليًا.</p></div>';return true}}
  window.AGCH_LIVEKIT_VIEWER={render,destroy(container){const r=rooms.get(container);try{r?.disconnect()}catch{}rooms.delete(container)}};
})();