(() => {
'use strict';
const cfg=window.AGCH_CONFIG||{},main=document.getElementById('appMain');if(!main||!cfg.supabaseUrl||!cfg.supabaseKey)return;
const H={apikey:cfg.supabaseKey,Authorization:`Bearer ${cfg.supabaseKey}`},esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let D;
async function get(path){const r=await fetch(`${cfg.supabaseUrl}/rest/v1/${path}`,{headers:H,cache:'no-store'});if(!r.ok)throw Error(path);return r.json()}
async function load(){const [t,r,a,m,teams,s]=await Promise.all([get('tournaments?select=id,slug,name,short_name,season'),get('referees?select=*'),get('referee_assignments?select=id,referee_id,tournament_id,category,role,name,photo_url,match_id'),get('matches?select=id,tournament_id,team_a_id,team_b_id,match_date,match_time,venue,stage,status,score_a,score_b&order=match_date.desc'),get('teams?select=id,name,logo_url'),get('referee_event_stats_v2?select=*')]);return D={tournaments:t,refs:r,assign:a,matches:m,teams,stats:s}}
const slug=()=>{const p=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);return p[0]==='tournament'?p[1]:''},team=id=>D.teams.find(x=>x.id===id),assign=r=>D.assign.filter(x=>x.referee_id===r.id&&x.match_id),sum=(r,k)=>D.stats.filter(x=>x.referee_id===r.id).reduce((n,x)=>n+(+x[k]||0),0);
function matchRow(a){const m=D.matches.find(x=>x.id===a.match_id);if(!m)return'';const A=team(m.team_a_id),B=team(m.team_b_id),st=D.stats.find(x=>x.referee_id===a.referee_id&&x.match_id===m.id);return `<button class="agh-ref-match" data-match-id="${m.id}"><div><small>${esc(m.match_date||'—')} · ${esc((m.match_time||'').slice(0,5))}</small><b>${esc(A?.name||'فريق')} <em>${m.status==='انتهت'?`${m.score_a??0} - ${m.score_b??0}`:'—'}</em> ${esc(B?.name||'فريق')}</b><span>${esc(m.stage||'مباراة')} · ${a.role==='main'?'حكم رئيسي':'حكم مساعد'}</span>${a.role==='main'?`<small>🟨 ${st?.yellow_cards||0} · 🟥 ${st?.red_cards||0} · ⚽ ${st?.penalties||0}</small>`:''}</div></button>`}
function profile(r){const a=assign(r),mainN=a.filter(x=>x.role==='main').length,assist=a.length-mainN,photo=r.photo_url?`<img src="${esc(r.photo_url)}" alt="${esc(r.name)}">`:'⚖️';let x=document.getElementById('aghRefModal');if(!x){x=document.createElement('div');x.id='aghRefModal';x.className='agh-ref-modal';document.body.appendChild(x)}x.innerHTML=`<div class="agh-ref-sheet"><button class="agh-ref-close" type="button">×</button><div class="agh-ref-profile"><div class="agh-ref-profile-photo">${photo}</div><div><small>REFEREE PROFILE</small><h2>${esc(r.name)}</h2><p>السجل التحكيمي الديناميكي</p></div></div><div class="agh-ref-stats"><div><b>${a.length}</b><span>المباريات</span></div><div><b>${mainN}</b><span>رئيسي</span></div><div><b>${assist}</b><span>مساعد</span></div><div><b>${sum(r,'yellow_cards')}</b><span>🟨 صفراء</span></div><div><b>${sum(r,'red_cards')}</b><span>🟥 حمراء</span></div><div><b>${sum(r,'penalties')}</b><span>⚽ جزاء</span></div></div><h3>المباريات</h3><div class="agh-ref-matches">${a.length?a.map(matchRow).join(''):'<p>لا توجد مباريات.</p>'}</div></div>`;x.classList.add('open')}
function card(r,t){const a=D.assign.filter(x=>x.referee_id===r.id&&x.tournament_id===t.id&&x.match_id),mainN=a.filter(x=>x.role==='main').length;return `<button type="button" class="agh-referee-card" data-referee-id="${r.id}"><div class="agh-referee-avatar">${r.photo_url?`<img src="${esc(r.photo_url)}" alt="${esc(r.name)}" loading="lazy">`:'⚖️'}</div><div class="agh-referee-copy"><b>${esc(r.name)}</b><small>${a.length} مباراة · ${mainN} رئيسي · ${a.length-mainN} مساعد</small><span>🟨 ${sum(r,'yellow_cards')} · 🟥 ${sum(r,'red_cards')} · ⚽ ${sum(r,'penalties')}</span></div><i>‹</i></button>`}
async function inject(){const s=slug();if(!s)return;main.querySelector('.agh-referees-section')?.remove();try{await load();const t=D.tournaments.find(x=>x.slug===s);if(!t)return;const ids=new Set(D.assign.filter(x=>x.tournament_id===t.id).map(x=>x.referee_id).filter(Boolean)),refs=D.refs.filter(x=>ids.has(x.id));const shell=main.querySelector('.page-shell');if(!shell||!refs.length)return;const sec=document.createElement('section');sec.className='section-block agh-referees-section';sec.innerHTML=`<div class="agh-referees-heading"><div><span>OFFICIALS</span><h2>الحكام والإحصائيات</h2><p>إحصائيات محسوبة تلقائيًا من أحداث المباريات الحقيقية.</p></div></div><div class="agh-referee-grid">${refs.map(r=>card(r,t)).join('')}</div>`;shell.appendChild(sec)}catch(e){console.warn(e)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-referee-id]');if(b&&D){const r=D.refs.find(x=>x.id===b.dataset.refereeId);if(r)profile(r)}if(e.target.closest('.agh-ref-close')||e.target.id==='aghRefModal')document.getElementById('aghRefModal')?.classList.remove('open');const m=e.target.closest('[data-match-id]');if(m){document.getElementById('aghRefModal')?.classList.remove('open');location.hash=`#/match/${m.dataset.matchId}`}},true);new MutationObserver(()=>setTimeout(inject,80)).observe(main,{childList:true,subtree:false});addEventListener('hashchange',()=>setTimeout(inject,120));setTimeout(inject,350);
})();