(() => {
  'use strict';
  const cfg=window.AGCH_CONFIG||{};
  const main=document.getElementById('appMain');
  if(!main||!cfg.supabaseUrl||!cfg.supabaseKey)return;
  let stories=[], timer=null, current=0;
  const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const api=async()=>{
    const url=`${cfg.supabaseUrl}/rest/v1/news?select=id,title,description,image_url,video_url,gallery_urls,is_story,story_pinned,story_expires_at,status,story_duration_seconds,created_at&is_story=eq.true&status=eq.published&order=story_pinned.desc,created_at.desc`;
    const r=await fetch(url,{headers:{apikey:cfg.supabaseKey,Authorization:`Bearer ${cfg.supabaseKey}`},cache:'no-store'});
    if(!r.ok)throw new Error('stories fetch failed'); return r.json();
  };
  const live=s=>s&&(s.story_pinned||!s.story_expires_at||new Date(s.story_expires_at)>new Date());
  function styles(){if(document.getElementById('aghNativeStoryCSS'))return;const s=document.createElement('style');s.id='aghNativeStoryCSS';s.textContent=`
  .agh-stories{margin:8px 0 22px}.agh-stories-title{display:flex;align-items:center;justify-content:space-between;margin:0 2px 10px}.agh-stories-title b{font:900 18px Cairo,sans-serif}.agh-stories-title span{font:700 11px Cairo,sans-serif;opacity:.6}.agh-stories-row{display:flex;gap:14px;overflow-x:auto;padding:3px 2px 8px;scrollbar-width:none}.agh-stories-row::-webkit-scrollbar{display:none}.agh-story{flex:0 0 78px;border:0;background:none;color:inherit;padding:0;text-align:center}.agh-story-ring{display:block;width:72px;height:72px;margin:auto;padding:3px;border-radius:50%;background:linear-gradient(135deg,#d7ff3f,#8b5cf6,#ff3b30)}.agh-story-ring>i{display:block;width:100%;height:100%;border-radius:50%;overflow:hidden;border:3px solid #090b09;background:#151515}.agh-story-ring img{width:100%;height:100%;object-fit:cover}.agh-story b{display:block;margin-top:6px;font:700 11px/1.4 Cairo,sans-serif;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agh-story-layer[hidden]{display:none!important}.agh-story-layer{position:fixed;inset:0;z-index:2147483647;background:#000;display:flex;justify-content:center;align-items:center}.agh-story-stage{position:relative;width:min(100vw,560px);height:100dvh;min-height:100vh;background:#000;overflow:hidden}.agh-story-stage>img,.agh-story-stage>video{width:100%;height:100%;object-fit:contain;background:#000}.agh-story-progress{position:absolute;z-index:5;top:max(12px,env(safe-area-inset-top));left:12px;right:12px;height:4px;border-radius:10px;background:#ffffff40;overflow:hidden}.agh-story-progress i{display:block;height:100%;background:#fff;width:0}.agh-story-close{position:absolute;z-index:6;top:max(25px,calc(env(safe-area-inset-top) + 12px));right:16px;width:44px;height:44px;border:0;border-radius:50%;background:#0009;color:#fff;font-size:29px}.agh-story-copy{position:absolute;z-index:5;right:18px;left:18px;bottom:max(32px,env(safe-area-inset-bottom));color:#fff;text-align:right;text-shadow:0 2px 14px #000}.agh-story-copy h2{font:900 22px/1.4 Cairo,sans-serif;margin:0}.agh-story-copy p{font:600 14px/1.8 Cairo,sans-serif;margin:7px 0 0}.agh-story-nav{position:absolute;z-index:4;top:70px;bottom:100px;width:42%;border:0;background:transparent}.agh-story-prev{left:0}.agh-story-next{right:0}@keyframes aghStoryRun{from{width:0}to{width:100%}}
  `;document.head.appendChild(s)}
  function close(){clearTimeout(timer);const l=document.getElementById('aghStoryLayer');if(l)l.hidden=true;document.body.style.overflow=''}
  function open(i){if(!stories.length)return;current=(i+stories.length)%stories.length;const x=stories[current],duration=Math.max(3,Number(x.story_duration_seconds||10));let l=document.getElementById('aghStoryLayer');if(!l){l=document.createElement('div');l.id='aghStoryLayer';l.className='agh-story-layer';document.body.appendChild(l)}clearTimeout(timer);document.body.style.overflow='hidden';const media=x.video_url?`<video src="${esc(x.video_url)}" autoplay muted playsinline></video>`:`<img src="${esc(x.image_url||(Array.isArray(x.gallery_urls)?x.gallery_urls[0]:'')||'assets/tournament.jpg')}" alt="${esc(x.title)}">`;l.innerHTML=`<div class="agh-story-stage"><div class="agh-story-progress"><i style="animation:aghStoryRun ${duration}s linear forwards"></i></div><button class="agh-story-close">×</button>${media}<button class="agh-story-nav agh-story-prev"></button><button class="agh-story-nav agh-story-next"></button><div class="agh-story-copy"><h2>${esc(x.title)}</h2>${x.description?`<p>${esc(x.description)}</p>`:''}</div></div>`;l.hidden=false;l.querySelector('.agh-story-close').onclick=close;l.querySelector('.agh-story-prev').onclick=()=>open(current-1);l.querySelector('.agh-story-next').onclick=()=>open(current+1);timer=setTimeout(()=>current<stories.length-1?open(current+1):close(),duration*1000)}
  function mount(){if(location.hash!=='#news')return;const page=main.querySelector('.news-center-page,.page-shell');if(!page)return;page.querySelectorAll('[data-news-open],.news-card').forEach(el=>{const id=(el.dataset.newsOpen||el.dataset.route?.split('/')[1]);if(id&&stories.some(s=>s.id===id))el.remove()});let box=page.querySelector('.agh-stories');if(!box){box=document.createElement('section');box.className='agh-stories';const head=page.querySelector('.news-center-head,.page-heading');if(head)head.insertAdjacentElement('afterend',box);else page.prepend(box)}box.innerHTML=`<div class="agh-stories-title"><b>Stories</b><span>آخر لحظات البطولة</span></div><div class="agh-stories-row">${stories.map((x,i)=>`<button class="agh-story" data-agh-story="${i}"><span class="agh-story-ring"><i><img src="${esc(x.image_url||(Array.isArray(x.gallery_urls)?x.gallery_urls[0]:'')||'assets/tournament.jpg')}" alt="${esc(x.title)}"></i></span><b>${esc(x.title)}</b></button>`).join('')}</div>`;box.hidden=!stories.length;box.querySelectorAll('[data-agh-story]').forEach(b=>b.onclick=()=>open(Number(b.dataset.aghStory)))}
  async function refresh(){if(location.hash!=='#news')return;try{stories=(await api()).filter(live);styles();mount()}catch(e){console.error(e)}}
  document.addEventListener('click',e=>{if(e.target.closest('[data-route="news"]'))setTimeout(refresh,500)},true);window.addEventListener('hashchange',()=>setTimeout(refresh,300));window.addEventListener('load',()=>setTimeout(refresh,700));let wait;new MutationObserver(()=>{if(location.hash==='#news'){clearTimeout(wait);wait=setTimeout(mount,80)}}).observe(main,{childList:true,subtree:true});styles();setTimeout(refresh,500);
})();