(() => {
  'use strict';
  const cfg=window.AGCH_CONFIG;
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});
  window.AGCH_ADMIN_SB=sb;
  const $=id=>document.getElementById(id);
  const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const CATS=['الكبار','الوسط','الصغار'];
  const EVENT_TYPES=['هدف','هدف عكسي','ركلة جزاء مسجلة','ركلة جزاء ضائعة','تمريرة حاسمة','بطاقة صفراء','بطاقة حمراء','تبديل','رجل المباراة','بداية المباراة','نهاية الشوط','نهاية المباراة'];
  const S={tournaments:[],teams:[],players:[],matches:[],events:[],news:[],refs:[],media:[],settings:null,audits:[],awards:[],user:null,loading:false};
  let liveChannel=null;
  const byId=(arr,id)=>arr.find(x=>x.id===id);
  const team=id=>byId(S.teams,id);
  const player=id=>byId(S.players,id);
  const match=id=>byId(S.matches,id);
  const mediaUrl=(u,f='../assets/tournament.jpg')=>!u?f:/^(https?:|data:|blob:)/i.test(u)?u:'../'+String(u).replace(/^\.\.\//,'').replace(/^\.\//,'');
  const img=(u,a='')=>`<img src="${esc(mediaUrl(u))}" alt="${esc(a)}" onerror="this.onerror=null;this.src='../assets/tournament.jpg'">`;
  const toast=(m,ok=true)=>{const t=$('toast');t.textContent=m;t.style.borderColor=ok?'#32634c':'#813c42';t.style.background=ok?'#193d2d':'#431e22';t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2300)};
  const confirmDelete=(label)=>window.confirm(`هل أنت متأكد من حذف ${label}؟`);
  const show=(html)=>{$('panel').innerHTML=html;$('sheet').classList.add('on')};
  const close=()=>{$('sheet').classList.remove('on');$('panel').innerHTML=''};
  const val=id=>$(id)?.value?.trim?.()??'';
  const nullable=v=>v===''?null:v;
  const debounce=(fn,ms=300)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
  const fmtDate=d=>d||'بدون تاريخ';
  const eventPlayerName=e=>e.player_name||player(e.player_id)?.name||'';
  const eventTeamName=e=>team(e.team_id)?.name||'';

  async function guard(){
    const {data:{user},error:authError}=await sb.auth.getUser();
    if(authError||!user){location.replace('login.html');return false}
    const {data:admin,error}=await sb.from('admin_emails').select('email').eq('email',user.email).maybeSingle();
    if(error||!admin){await sb.auth.signOut();location.replace('login.html');return false}
    S.user=user;$('adminUser').textContent=user.email||'المسؤول';return true;
  }

  async function loadAll(silent=false){
    if(S.loading)return;S.loading=true;if(!silent)toast('جارٍ تحميل بيانات الإدارة...');
    try{
      const [tor,tr,pr,mr,er,nr,rr,med,sr,au,aw]=await Promise.all([
        sb.from('tournaments').select('*').order('sort_order'),
        sb.from('teams').select('*').order('category').order('name'),
        sb.from('players').select('*').order('name'),
        sb.from('matches').select('*,team_a:teams!matches_team_a_id_fkey(id,name,logo_url),team_b:teams!matches_team_b_id_fkey(id,name,logo_url)').order('match_date',{ascending:false,nullsFirst:false}),
        sb.from('match_events').select('*').order('created_at',{ascending:false}),
        sb.from('news').select('*').order('featured',{ascending:false}).order('sort_order').order('publish_date',{ascending:false}),
        sb.from('referee_assignments').select('*').order('category'),
        sb.from('media_assets').select('*').order('created_at',{ascending:false}),
        sb.from('site_settings').select('*').eq('id','main').maybeSingle(),
        sb.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(50),
        sb.from('awards').select('*,player:players(id,name,team_id,photo_url)').order('award_date',{ascending:false,nullsFirst:false})
      ]);
      const bad=[tor,tr,pr,mr,er,nr,rr,med,sr,au,aw].find(x=>x.error);if(bad)throw bad.error;
      S.tournaments=tor.data||[];S.teams=tr.data||[];S.players=pr.data||[];S.matches=mr.data||[];S.events=er.data||[];S.news=nr.data||[];S.refs=rr.data||[];S.media=med.data||[];S.settings=sr.data||{};S.audits=au.data||[];S.awards=aw.data||[];
      renderAll();
    }catch(e){console.error(e);toast('تعذر تحميل بعض بيانات الإدارة',false)}finally{S.loading=false}
  }

  function renderAll(){renderDashboard();renderTournaments();renderTeams();renderPlayers();renderMatches();renderEvents();renderRefs();renderNews();renderAwards();renderSettings();renderMedia()}
  function renderDashboard(){
    $('stTeams').textContent=S.teams.length;$('stPlayers').textContent=S.players.length;$('stMatches').textContent=S.matches.length;$('stFinished').textContent=S.matches.filter(m=>m.status==='انتهت').length;$('stUpcoming').textContent=S.matches.filter(m=>m.status==='قادمة').length;$('stGoals').textContent=S.events.filter(e=>['هدف','ركلة جزاء مسجلة','هدف عكسي'].includes(e.type)).length;
    $('auditList').innerHTML=S.audits.length?S.audits.slice(0,20).map(a=>`<div class="audit-row"><span>${esc(a.action)}</span><b>${esc(a.summary||a.record_id||'تعديل')}</b><small>${esc((a.created_at||'').replace('T',' ').slice(0,16))}</small></div>`).join(''):'<div class="empty">لا توجد تعديلات مسجلة بعد</div>';
  }

  function tournament(id){return byId(S.tournaments,id)}
  function renderTournaments(){if(!$('tournamentList'))return;const rows=S.tournaments;$('tournamentList').innerHTML=rows.length?rows.map(t=>`<div class="item">${img(t.logo_url,t.name)}<div class="meta"><b>${esc(t.name)}</b><small>${esc(t.season)} · ${esc(t.division)} · ${esc(t.status)} · ${S.teams.filter(x=>x.tournament_id===t.id).length} فريق</small></div><div class="actions"><button class="ghost" data-edit-tournament="${t.id}">تعديل</button><button class="danger" data-delete-tournament="${t.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد بطولات</div>'}
  function tournamentForm(id=null){const t=id?tournament(id):null;show(`<div class="panel-head"><h2>${t?'تعديل البطولة':'إضافة بطولة'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>اسم البطولة</label><input id="tofName" value="${esc(t?.name||'')}"></div><div class="field"><label>الاسم المختصر</label><input id="tofShort" value="${esc(t?.short_name||'')}"></div><div class="field"><label>الفئة</label><select id="tofDivision">${CATS.map(c=>`<option ${t?.division===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>الموسم</label><input id="tofSeason" value="${esc(t?.season||'2026')}"></div><div class="field"><label>الحالة</label><select id="tofStatus">${['قادمة','مستمرة','مكتملة','مؤجلة'].map(s=>`<option ${t?.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>لون البطولة</label><input id="tofAccent" type="color" value="${esc(t?.accent_color||'#c7ff37')}"></div><div class="field"><label>ترتيب العرض</label><input id="tofSort" type="number" value="${t?.sort_order??S.tournaments.length+1}"></div></div><div class="field"><label>الوصف</label><textarea id="tofDescription">${esc(t?.description||'')}</textarea></div><div class="uploadbox">${img(t?.logo_url,'شعار البطولة')}<div><label>شعار البطولة</label><input id="tofLogo" type="file" accept="image/*"></div></div><div class="savebar"><button id="saveTournament" class="primary">حفظ البطولة</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveTournament').onclick=()=>saveTournament(t?.id||null)}
  async function saveTournament(id){const name=val('tofName'),short_name=val('tofShort'),division=val('tofDivision'),season=val('tofSeason')||'2026';if(!name||!short_name)return toast('اسم البطولة والاسم المختصر مطلوبان',false);const duplicate=S.tournaments.find(t=>t.id!==id&&t.division===division);if(duplicate)return toast('توجد بطولة مرتبطة بهذه الفئة بالفعل',false);try{let logo_url=id?tournament(id)?.logo_url:null;const f=$('tofLogo').files[0];if(f)logo_url=await uploadFile(f,'tournament-logo',id);const slug=id?tournament(id).slug:`${division==='الكبار'?'seniors':division==='الوسط'?'middle':'juniors'}-${season}`;const payload={name,short_name,division,slug,season,status:val('tofStatus'),accent_color:val('tofAccent')||'#c7ff37',description:nullable(val('tofDescription')),sort_order:Number(val('tofSort')||0),logo_url};const {error}=await(id?sb.from('tournaments').update(payload).eq('id',id):sb.from('tournaments').insert(payload));if(error)throw error;toast('تم حفظ البطولة');close();await loadAll(true)}catch(e){toast('تعذر حفظ البطولة: '+e.message,false)}}
  async function deleteTournament(id){const linked=S.teams.some(t=>t.tournament_id===id)||S.matches.some(m=>m.tournament_id===id);if(linked)return toast('لا يمكن حذف بطولة مرتبطة بفرق أو مباريات',false);if(!confirmDelete('هذه البطولة'))return;const {error}=await sb.from('tournaments').delete().eq('id',id);if(error)return toast('تعذر حذف البطولة: '+error.message,false);toast('تم حذف البطولة');await loadAll(true)}

  function renderTeams(){const q=val('teamSearch').toLowerCase(),cat=val('teamCategory')||'الكل';const a=S.teams.filter(t=>(cat==='الكل'||t.category===cat)&&(!q||t.name.toLowerCase().includes(q)));$('teamList').innerHTML=a.length?a.map(t=>`<div class="item">${img(t.logo_url,t.name)}<div class="meta"><b>${esc(t.name)}</b><small>${esc(t.category)}${t.group_name?` · المجموعة ${esc(t.group_name)}`:''} · ${S.players.filter(p=>p.team_id===t.id).length} لاعب${t.coach?` · المدرب: ${esc(t.coach)}`:''}</small></div><div class="actions"><button class="ghost" data-edit-team="${t.id}">تعديل</button><button class="danger" data-delete-team="${t.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد فرق مطابقة</div>'}

  function teamForm(id=null){const t=id?team(id):null;show(`<div class="panel-head"><h2>${t?'تعديل الفريق':'إضافة فريق'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>اسم الفريق</label><input id="tfName" value="${esc(t?.name||'')}"></div><div class="field"><label>البطولة</label><select id="tfTournament">${S.tournaments.map(x=>`<option value="${x.id}" ${t?.tournament_id===x.id?'selected':''}>${esc(x.short_name)} · ${esc(x.season)}</option>`).join('')}</select></div><div class="field"><label>المجموعة</label><input id="tfGroup" value="${esc(t?.group_name||'')}" placeholder="A / B / C أو اتركها فارغة"></div><div class="field"><label>المدرب</label><input id="tfCoach" value="${esc(t?.coach||'')}"></div><div class="field"><label>القائد</label><input id="tfCaptain" value="${esc(t?.captain||'')}"></div><div class="field"><label>صورة الفريق (اختيارية)</label><input id="tfTeamPhoto" type="file" accept="image/*"></div></div><div class="field"><label>وصف الفريق</label><textarea id="tfDesc">${esc(t?.description||'')}</textarea></div><div class="uploadbox"><img id="teamLogoPreview" src="${esc(mediaUrl(t?.logo_url))}"><div><label>شعار الفريق</label><input id="tfLogo" type="file" accept="image/*"><p class="muted">ارفع الشعار من هنا؛ لا حاجة لكتابة مسار يدويًا.</p></div></div><div class="savebar"><button class="primary" id="saveTeam">${t?'حفظ التغييرات':'إضافة الفريق'}</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveTeam').onclick=()=>saveTeam(t?.id||null)}
  async function saveTeam(id){const name=val('tfName'),tournament_id=val('tfTournament'),tour=tournament(tournament_id),category=tour?.division;if(!name||!tournament_id||!category)return toast('اسم الفريق والبطولة مطلوبان',false);const dup=S.teams.find(t=>t.id!==id&&t.tournament_id===tournament_id&&t.name.trim()===name);if(dup)return toast('يوجد فريق بنفس الاسم داخل هذه البطولة',false);try{let logo=id?team(id)?.logo_url:null,photo=id?team(id)?.team_photo_url:null;const lf=$('tfLogo').files[0],pf=$('tfTeamPhoto').files[0];if(lf)logo=await uploadFile(lf,'team-logo',id);if(pf)photo=await uploadFile(pf,'team-photo',id);const payload={name,tournament_id,category,group_name:nullable(val('tfGroup')),coach:nullable(val('tfCoach')),captain:nullable(val('tfCaptain')),description:nullable(val('tfDesc')),logo_url:logo,team_photo_url:photo,updated_at:new Date().toISOString()};const q=id?sb.from('teams').update(payload).eq('id',id):sb.from('teams').insert(payload);const {error}=await q;if(error)throw error;toast('تم حفظ الفريق بنجاح');close();await loadAll(true)}catch(e){console.error(e);toast('تعذر حفظ الفريق: '+e.message,false)}}
  async function deleteTeam(id){const t=team(id);if(!confirmDelete(`الفريق «${t?.name||''}»`))return;const linked=S.matches.some(m=>m.team_a_id===id||m.team_b_id===id)||S.players.some(p=>p.team_id===id);if(linked&&!window.confirm('الفريق مرتبط بلاعبين أو مباريات. قد ترفض قاعدة البيانات الحذف. هل تريد المحاولة؟'))return;const {error}=await sb.from('teams').delete().eq('id',id);if(error)return toast('تعذر حذف الفريق لأنه مرتبط ببيانات أخرى',false);toast('تم حذف الفريق');await loadAll(true)}

  function renderPlayers(){const q=val('playerSearch').toLowerCase(),tid=val('playerTeamFilter'),cat=val('playerCategory')||'الكل';const a=S.players.filter(p=>(!tid||p.team_id===tid)&&(cat==='الكل'||team(p.team_id)?.category===cat)&&(!q||p.name.toLowerCase().includes(q)||team(p.team_id)?.name?.toLowerCase().includes(q)));$('playerList').innerHTML=a.length?a.slice(0,400).map(p=>{const t=team(p.team_id);return `<div class="item">${img(p.photo_url||t?.logo_url,p.name)}<div class="meta"><b>${esc(p.name)}${p.is_captain?' · القائد':''}</b><small>${esc(t?.name||'غير محدد')}${p.position?` · ${esc(p.position)}`:''}${p.number!=null?` · #${p.number}`:''}</small></div><div class="actions"><button class="ghost" data-edit-player="${p.id}">تعديل</button><button class="ghost" data-player-events="${p.id}">إحصائيات</button><button class="danger" data-delete-player="${p.id}">حذف</button></div></div>`}).join(''):'<div class="empty card">لا يوجد لاعبون مطابقون</div>'}
  function refreshTeamFilters(){const opts='<option value="">كل الفرق</option>'+S.teams.map(t=>`<option value="${t.id}">${esc(t.name)} · ${esc(t.category)}</option>`).join('');if($('playerTeamFilter'))$('playerTeamFilter').innerHTML=opts;if($('eventMatchFilter'))$('eventMatchFilter').innerHTML='<option value="">كل المباريات</option>'+S.matches.map(m=>`<option value="${m.id}">${esc(m.team_a?.name||'')} × ${esc(m.team_b?.name||'')} · ${esc(m.category)}</option>`).join('')}
  function playerForm(id=null){const p=id?player(id):null;show(`<div class="panel-head"><h2>${p?'تعديل اللاعب':'إضافة لاعب'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="field"><label>الفريق</label><select id="pfTeam">${S.teams.map(t=>`<option value="${t.id}" ${p?.team_id===t.id?'selected':''}>${esc(t.name)} · ${esc(t.category)}</option>`).join('')}</select></div><div class="row two"><div class="field"><label>اسم اللاعب</label><input id="pfName" value="${esc(p?.name||'')}"></div><div class="field"><label>رقم اللاعب (اختياري)</label><input id="pfNumber" type="number" min="0" value="${p?.number??''}"></div><div class="field"><label>المركز (اختياري)</label><select id="pfPos"><option value="">غير محدد</option>${['حارس مرمى','دفاع','وسط','هجوم'].map(x=>`<option ${p?.position===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>القائد</label><select id="pfCaptain"><option value="false" ${!p?.is_captain?'selected':''}>لا</option><option value="true" ${p?.is_captain?'selected':''}>نعم</option></select></div></div><div class="field"><label>ملاحظات</label><textarea id="pfNotes">${esc(p?.notes||'')}</textarea></div><div class="uploadbox">${img(p?.photo_url||team(p?.team_id)?.logo_url,p?.name||'')}<div><label>صورة اللاعب</label><input id="pfPhoto" type="file" accept="image/*"><p class="muted">الإحصائيات الرياضية لا تُكتب يدويًا هنا؛ تُحسب من أحداث المباريات.</p></div></div><div class="savebar"><button id="savePlayer" class="primary">حفظ اللاعب</button><button class="ghost" data-close>إلغاء</button></div>`);$('savePlayer').onclick=()=>savePlayer(p?.id||null)}
  async function savePlayer(id){const name=val('pfName'),team_id=val('pfTeam');if(!name||!team_id)return toast('اسم اللاعب والفريق مطلوبان',false);const dup=S.players.find(p=>p.id!==id&&p.team_id===team_id&&p.name.trim()===name);if(dup&&!window.confirm('يوجد لاعب بنفس الاسم داخل الفريق. هل تريد حفظ لاعب آخر بنفس الاسم؟'))return;try{let photo=id?player(id)?.photo_url:null;const f=$('pfPhoto').files[0];if(f)photo=await uploadFile(f,'player-photo',id);const payload={team_id,name,number:nullable(val('pfNumber'))===null?null:Number(val('pfNumber')),position:nullable(val('pfPos')),is_captain:val('pfCaptain')==='true',notes:nullable(val('pfNotes')),photo_url:photo,updated_at:new Date().toISOString()};const {error}=await(id?sb.from('players').update(payload).eq('id',id):sb.from('players').insert(payload));if(error)throw error;toast('تم حفظ اللاعب');close();await loadAll(true)}catch(e){console.error(e);toast('تعذر حفظ اللاعب: '+e.message,false)}}
  async function deletePlayer(id){const p=player(id);const linked=S.events.filter(e=>e.player_id===id||e.assist_player_id===id).length;if(linked&&!window.confirm(`لدى هذا اللاعب ${linked} حدثًا مرتبطًا. الحذف قد يُرفض أو يؤثر على الربط. هل تريد المتابعة؟`))return;if(!confirmDelete(`اللاعب «${p?.name||''}»`))return;const {error}=await sb.from('players').delete().eq('id',id);if(error)return toast('تعذر حذف اللاعب لوجود بيانات مرتبطة به',false);toast('تم حذف اللاعب');await loadAll(true)}
  function playerStatsSheet(id){const p=player(id),t=team(p?.team_id),ev=S.events.filter(e=>e.player_id===id||e.assist_player_id===id||(!e.player_id&&e.player_name===p?.name&&e.team_id===p?.team_id)),goals=ev.filter(e=>e.player_id===id&&['هدف','ركلة جزاء مسجلة'].includes(e.type)).length,assists=ev.filter(e=>(e.type==='تمريرة حاسمة'&&e.player_id===id)||e.assist_player_id===id).length,y=ev.filter(e=>e.player_id===id&&e.type==='بطاقة صفراء').length,r=ev.filter(e=>e.player_id===id&&e.type==='بطاقة حمراء').length,m=ev.filter(e=>e.player_id===id&&e.type==='رجل المباراة').length;show(`<div class="panel-head"><h2>${esc(p?.name||'')}</h2><button class="ghost" data-close>إغلاق</button></div><p class="muted">${esc(t?.name||'')}</p><div class="dashboard-grid"><div class="metric"><b>${goals}</b><span>أهداف</span></div><div class="metric"><b>${assists}</b><span>صناعة</span></div><div class="metric"><b>${y}</b><span>صفراء</span></div><div class="metric"><b>${r}</b><span>حمراء</span></div><div class="metric"><b>${m}</b><span>رجل المباراة</span></div></div><p class="muted">هذه الأرقام مشتقة مباشرة من أحداث المباريات.</p>`)}

  function renderMatches(){const cat=val('matchCategory')||'الكل',st=val('matchStatus')||'الكل';const a=S.matches.filter(m=>(cat==='الكل'||m.category===cat)&&(st==='الكل'||m.status===st));$('matchList').innerHTML=a.length?a.map(m=>`<div class="item">${img(m.team_a?.logo_url,m.team_a?.name||'')}<div class="meta"><b>${esc(m.team_a?.name||'')} <span>${m.status==='انتهت'||m.status==='مباشر'?`${m.score_a??0} - ${m.score_b??0}`:'VS'}</span> ${esc(m.team_b?.name||'')}</b><small>${esc(m.category)} · ${esc(m.status)} · ${esc(m.match_date||'بدون تاريخ')} ${(m.match_time||'').slice(0,5)}${m.group_name?` · المجموعة ${esc(m.group_name)}`:''}</small></div><div class="actions">${m.status==='قادمة'?`<button class="primary" data-start-match="${m.id}">بدء</button>`:''}${m.status==='مباشر'?`<button class="primary" data-finish-match="${m.id}">إنهاء</button>`:''}<button class="ghost" data-match-events="${m.id}">الأحداث</button><button class="ghost" data-edit-match="${m.id}">تعديل</button><button class="danger" data-delete-match="${m.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد مباريات مطابقة</div>'}
  function matchForm(id=null){const m=id?match(id):null;show(`<div class="panel-head"><h2>${m?'تعديل المباراة':'إنشاء مباراة'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>البطولة</label><select id="mfTournament">${S.tournaments.map(t=>`<option value="${t.id}" ${m?.tournament_id===t.id?'selected':''}>${esc(t.short_name)} · ${esc(t.season)}</option>`).join('')}</select></div><div class="field"><label>المجموعة</label><input id="mfGroup" value="${esc(m?.group_name||'')}"></div></div><div class="row two"><div class="field"><label>الفريق الأول</label><select id="mfA"></select></div><div class="field"><label>الفريق الثاني</label><select id="mfB"></select></div></div><div class="row two"><div class="field"><label>المرحلة</label><input id="mfStage" value="${esc(m?.stage||'')}"></div><div class="field"><label>الجولة</label><input id="mfRound" value="${esc(m?.round_name||'')}"></div><div class="field"><label>التاريخ</label><input id="mfDate" type="date" value="${esc(m?.match_date||'')}"></div><div class="field"><label>الوقت</label><input id="mfTime" type="time" value="${esc((m?.match_time||'').slice(0,5))}"></div><div class="field"><label>الملعب</label><input id="mfVenue" value="${esc(m?.venue||'')}"></div><div class="field"><label>الحالة</label><select id="mfStatus">${['قادمة','مباشر','انتهت','مؤجلة','ملغاة'].map(s=>`<option ${m?.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>نتيجة الفريق الأول</label><input id="mfScoreA" type="number" min="0" value="${m?.score_a??''}"></div><div class="field"><label>نتيجة الفريق الثاني</label><input id="mfScoreB" type="number" min="0" value="${m?.score_b??''}"></div></div><div class="savebar"><button id="saveMatch" class="primary">حفظ المباراة</button><button class="ghost" data-close>إلغاء</button></div>`);const fillTeams=()=>{const tournament_id=val('mfTournament'),arr=S.teams.filter(t=>t.tournament_id===tournament_id),opts=arr.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('mfA').innerHTML=opts;$('mfB').innerHTML=opts;if(m){$('mfA').value=m.team_a_id;$('mfB').value=m.team_b_id}};$('mfTournament').onchange=fillTeams;fillTeams();$('saveMatch').onclick=()=>saveMatch(m?.id||null)}
  async function saveMatch(id){const team_a_id=val('mfA'),team_b_id=val('mfB'),tournament_id=val('mfTournament'),tour=tournament(tournament_id),category=tour?.division;if(!team_a_id||!team_b_id||!tournament_id)return toast('اختر البطولة والفريقين',false);if(team_a_id===team_b_id)return toast('لا يمكن اختيار الفريق نفسه مرتين',false);if(team(team_a_id)?.tournament_id!==tournament_id||team(team_b_id)?.tournament_id!==tournament_id)return toast('الفريقان يجب أن يكونا من البطولة المختارة',false);const duplicate=S.matches.find(m=>m.id!==id&&m.tournament_id===tournament_id&&((m.team_a_id===team_a_id&&m.team_b_id===team_b_id)||(m.team_a_id===team_b_id&&m.team_b_id===team_a_id))&&m.match_date===nullable(val('mfDate'))&&m.match_time?.slice(0,5)===nullable(val('mfTime')));if(duplicate)return toast('توجد مباراة بنفس الفريقين والموعد داخل البطولة',false);const payload={team_a_id,team_b_id,tournament_id,category,group_name:nullable(val('mfGroup')),stage:nullable(val('mfStage')),round_name:nullable(val('mfRound')),match_date:nullable(val('mfDate')),match_time:nullable(val('mfTime')),venue:nullable(val('mfVenue')),status:val('mfStatus'),score_a:nullable(val('mfScoreA'))===null?null:Number(val('mfScoreA')),score_b:nullable(val('mfScoreB'))===null?null:Number(val('mfScoreB')),updated_at:new Date().toISOString()};const {error}=await(id?sb.from('matches').update(payload).eq('id',id):sb.from('matches').insert(payload));if(error)return toast('تعذر حفظ المباراة: '+error.message,false);toast('تم حفظ المباراة وإعادة احتساب الإحصائيات');close();await loadAll(true)}
  async function setMatchStatus(id,status){if(status==='انتهت'&&!window.confirm('هل تريد إنهاء المباراة بالنتيجة الحالية؟'))return;const payload={status,updated_at:new Date().toISOString()};if(status==='مباشر'){const m=match(id);if(m.score_a==null)payload.score_a=0;if(m.score_b==null)payload.score_b=0}const {error}=await sb.from('matches').update(payload).eq('id',id);if(error)return toast('تعذر تحديث حالة المباراة',false);toast(status==='مباشر'?'بدأت المباراة وأصبحت مباشرة':'تم إنهاء المباراة');await loadAll(true)}
  async function deleteMatch(id){const m=match(id);if(!confirmDelete(`المباراة «${m?.team_a?.name||''} × ${m?.team_b?.name||''}»`))return;const linked=S.events.filter(e=>e.match_id===id).length;if(linked&&!window.confirm(`توجد ${linked} أحداث مرتبطة بهذه المباراة وقد يمنع ذلك الحذف. هل تريد المحاولة؟`))return;const {error}=await sb.from('matches').delete().eq('id',id);if(error)return toast('تعذر حذف المباراة لوجود بيانات مرتبطة بها',false);toast('تم حذف المباراة');await loadAll(true)}

  function renderEvents(){const mid=val('eventMatchFilter'),a=S.events.filter(e=>!mid||e.match_id===mid);$('eventsList').innerHTML=a.length?a.slice(0,300).map(e=>{const m=match(e.match_id);return `<div class="item"><div class="meta"><b><span class="event-chip">${esc(e.type)}</span> ${esc(eventPlayerName(e)||e.note||'بدون لاعب')}</b><small>${esc(m?.team_a?.name||'')} × ${esc(m?.team_b?.name||'')}${e.minute!=null?` · الدقيقة ${e.minute}`:''}${eventTeamName(e)?` · ${esc(eventTeamName(e))}`:''}</small></div><div class="actions"><button class="ghost" data-edit-event="${e.id}">تعديل</button><button class="danger" data-delete-event="${e.id}">حذف</button></div></div>`}).join(''):'<div class="empty card">لا توجد أحداث مسجلة</div>'}
  function openEventsForMatch(id){activateTab('events');$('eventMatchFilter').value=id;renderEvents();eventForm(null,id)}
  function eventForm(id=null,forcedMatch=null){const e=id?byId(S.events,id):null,mid=forcedMatch||e?.match_id||S.matches[0]?.id||'';show(`<div class="panel-head"><h2>${e?'تعديل الحدث':'إضافة حدث للمباراة'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="field"><label>المباراة</label><select id="efMatch">${S.matches.map(m=>`<option value="${m.id}" ${(mid===m.id)?'selected':''}>${esc(m.team_a?.name||'')} × ${esc(m.team_b?.name||'')} · ${esc(m.category)}</option>`).join('')}</select></div><div class="row two"><div class="field"><label>نوع الحدث</label><select id="efType">${EVENT_TYPES.map(t=>`<option ${e?.type===t?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label>الدقيقة</label><input id="efMinute" type="number" min="0" max="200" value="${e?.minute??''}"></div></div><div class="field"><label>الفريق</label><select id="efTeam"></select></div><div class="field"><label>اللاعب</label><select id="efPlayer"></select></div><div id="assistWrap" class="field"><label>صانع الهدف (اختياري)</label><select id="efAssist"></select></div><div class="field"><label>ملاحظة</label><textarea id="efNote">${esc(e?.note||'')}</textarea></div><div class="savebar"><button id="saveEvent" class="primary">حفظ الحدث</button><button class="ghost" data-close>إلغاء</button></div>`);const fill=()=>{const m=match(val('efMatch'));if(!m)return;const teams=[team(m.team_a_id),team(m.team_b_id)].filter(Boolean);$('efTeam').innerHTML='<option value="">بدون فريق</option>'+teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');if(e?.team_id&&teams.some(t=>t.id===e.team_id))$('efTeam').value=e.team_id;else if(!$('efTeam').value&&teams[0])$('efTeam').value=teams[0].id;fillPlayers()};const fillPlayers=()=>{const tid=val('efTeam'),ps=S.players.filter(p=>p.team_id===tid);$('efPlayer').innerHTML='<option value="">بدون لاعب</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('efAssist').innerHTML='<option value="">لا توجد صناعة</option>'+ps.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if(e?.player_id&&ps.some(p=>p.id===e.player_id))$('efPlayer').value=e.player_id;if(e?.assist_player_id&&ps.some(p=>p.id===e.assist_player_id))$('efAssist').value=e.assist_player_id};const toggleAssist=()=>{$('assistWrap').style.display=['هدف','ركلة جزاء مسجلة'].includes(val('efType'))?'block':'none'};$('efMatch').onchange=fill;$('efTeam').onchange=fillPlayers;$('efType').onchange=toggleAssist;fill();fillPlayers();toggleAssist();$('saveEvent').onclick=()=>saveEvent(e?.id||null)}
  async function saveEvent(id){const match_id=val('efMatch'),type=val('efType'),team_id=nullable(val('efTeam')),player_id=nullable(val('efPlayer')),assist_player_id=nullable(val('efAssist')),minute=nullable(val('efMinute'));if(!match_id||!type)return toast('المباراة ونوع الحدث مطلوبان',false);const old=id?byId(S.events,id):null,p=player(player_id),ap=player(assist_player_id);const payload={match_id,type,team_id,player_id,assist_player_id:['هدف','ركلة جزاء مسجلة'].includes(type)?assist_player_id:null,minute:minute===null?null:Number(minute),note:nullable(val('efNote')),player_name:p?.name||old?.player_name||null,assist_name:ap?.name||old?.assist_name||null};try{if(type==='رجل المباراة'){let q=sb.from('match_events').delete().eq('match_id',match_id).eq('type','رجل المباراة');if(id)q=q.neq('id',id);const {error}=await q;if(error)throw error}const {error}=await(id?sb.from('match_events').update(payload).eq('id',id):sb.from('match_events').insert(payload));if(error)throw error;if(!id)await applyEventScoreDelta(payload,1);else if(old){await applyEventScoreDelta(old,-1);await applyEventScoreDelta(payload,1)}if(type==='بداية المباراة')await sb.from('matches').update({status:'مباشر',score_a:match(match_id)?.score_a??0,score_b:match(match_id)?.score_b??0,updated_at:new Date().toISOString()}).eq('id',match_id);if(type==='نهاية المباراة')await sb.from('matches').update({status:'انتهت',updated_at:new Date().toISOString()}).eq('id',match_id);toast('تم حفظ الحدث وتحديث الموقع');close();await loadAll(true)}catch(err){console.error(err);toast('تعذر حفظ الحدث: '+err.message,false)}}
  async function applyEventScoreDelta(e,delta){if(!['هدف','هدف عكسي','ركلة جزاء مسجلة'].includes(e.type)||!e.team_id)return;const m=match(e.match_id);if(!m)return;let sa=Number(m.score_a??0),sbv=Number(m.score_b??0);if(e.team_id===m.team_a_id)sa=Math.max(0,sa+delta);else if(e.team_id===m.team_b_id)sbv=Math.max(0,sbv+delta);else return;await sb.from('matches').update({score_a:sa,score_b:sbv,updated_at:new Date().toISOString()}).eq('id',m.id);m.score_a=sa;m.score_b=sbv}
  async function deleteEvent(id){const e=byId(S.events,id);if(!confirmDelete(`الحدث «${e?.type||''}»`))return;const {error}=await sb.from('match_events').delete().eq('id',id);if(error)return toast('تعذر حذف الحدث',false);await applyEventScoreDelta(e,-1);toast('تم حذف الحدث');await loadAll(true)}

  function renderRefs(){const a=S.refs;$('refsList').innerHTML=a.length?a.map(r=>`<div class="item"><div class="meta"><b>${esc(r.name)}</b><small>${esc(r.category)} · ${r.role==='main'?'الحكم الرئيسي':'الحكم المساعد'}${r.match_id?` · ${esc(match(r.match_id)?.team_a?.name||'')} × ${esc(match(r.match_id)?.team_b?.name||'')}`:' · عام للفئة'}</small></div><div class="actions"><button class="ghost" data-edit-ref="${r.id}">تعديل</button><button class="danger" data-delete-ref="${r.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد تعيينات حكام</div>'}
  function refForm(id=null){const r=id?byId(S.refs,id):null;show(`<div class="panel-head"><h2>${r?'تعديل الحكم':'إضافة حكم'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>اسم الحكم</label><input id="rfName" value="${esc(r?.name||'')}"></div><div class="field"><label>الفئة</label><select id="rfCat">${CATS.map(c=>`<option ${r?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>الدور</label><select id="rfRole"><option value="main" ${r?.role==='main'?'selected':''}>الحكم الرئيسي</option><option value="assistant" ${r?.role==='assistant'?'selected':''}>الحكم المساعد</option></select></div><div class="field"><label>مباراة محددة (اختياري)</label><select id="rfMatch"><option value="">عام للفئة</option>${S.matches.map(m=>`<option value="${m.id}" ${r?.match_id===m.id?'selected':''}>${esc(m.team_a?.name||'')} × ${esc(m.team_b?.name||'')}</option>`).join('')}</select></div></div><div class="savebar"><button id="saveRef" class="primary">حفظ الحكم</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveRef').onclick=()=>saveRef(r?.id||null)}
  async function saveRef(id){const name=val('rfName'),category=val('rfCat'),tournament_id=S.tournaments.find(t=>t.division===category)?.id||null;if(!name)return toast('اسم الحكم مطلوب',false);const payload={name,category,tournament_id,role:val('rfRole'),match_id:nullable(val('rfMatch'))};const {error}=await(id?sb.from('referee_assignments').update(payload).eq('id',id):sb.from('referee_assignments').insert(payload));if(error)return toast('تعذر حفظ الحكم: '+error.message,false);toast('تم حفظ الحكم');close();await loadAll(true)}
  async function deleteRef(id){if(!confirmDelete('تعيين الحكم'))return;const {error}=await sb.from('referee_assignments').delete().eq('id',id);if(error)return toast('تعذر حذف الحكم',false);toast('تم حذف الحكم');await loadAll(true)}

  function renderNews(){$('newsAdminList').innerHTML=S.news.length?S.news.map(n=>`<div class="item">${img(n.image_url,n.title)}<div class="meta"><b>${esc(n.title)}</b><small>${esc(n.publish_date||'')} · ${esc(n.type||'خبر')}${n.featured?' · مثبت':''}</small></div><div class="actions"><button class="ghost" data-edit-news="${n.id}">تعديل</button><button class="danger" data-delete-news="${n.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد أخبار منشورة</div>'}
  function newsForm(id=null){const n=id?byId(S.news,id):null;show(`<div class="panel-head"><h2>${n?'تعديل المنشور':'نشر خبر أو إعلان'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>العنوان</label><input id="nfTitle" value="${esc(n?.title||'')}"></div><div class="field"><label>التاريخ</label><input id="nfDate" type="date" value="${esc(n?.publish_date||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>النوع</label><select id="nfType">${['خبر','إعلان','تحديث','نتيجة','بيان'].map(x=>`<option ${n?.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>الفئة (اختياري)</label><select id="nfCat"><option value="">عام</option>${CATS.map(x=>`<option ${n?.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>ترتيب العرض</label><input id="nfSort" type="number" value="${n?.sort_order??0}"></div><div class="field"><label>مثبت</label><select id="nfFeatured"><option value="false" ${!n?.featured?'selected':''}>لا</option><option value="true" ${n?.featured?'selected':''}>نعم</option></select></div></div><div class="field"><label>ملخص قصير</label><textarea id="nfDesc">${esc(n?.description||'')}</textarea></div><div class="field"><label>النص الكامل</label><textarea id="nfContent" style="min-height:180px">${esc(n?.content||'')}</textarea></div><div class="uploadbox">${img(n?.image_url,'صورة الخبر')}<div><label>صورة المنشور</label><input id="nfImage" type="file" accept="image/*"></div></div><div class="savebar"><button id="saveNews" class="primary">نشر / حفظ</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveNews').onclick=()=>saveNews(n?.id||null)}
  async function saveNews(id){const title=val('nfTitle');if(!title)return toast('عنوان المنشور مطلوب',false);try{let image_url=id?byId(S.news,id)?.image_url:null;const f=$('nfImage').files[0];if(f)image_url=await uploadFile(f,'news',id);const category=nullable(val('nfCat')),tournament_id=S.tournaments.find(t=>t.division===category)?.id||null;const payload={title,description:nullable(val('nfDesc')),content:nullable(val('nfContent')),publish_date:val('nfDate')||new Date().toISOString().slice(0,10),type:nullable(val('nfType')),category,tournament_id,sort_order:Number(val('nfSort')||0),featured:val('nfFeatured')==='true',image_url,updated_at:new Date().toISOString()};const {error}=await(id?sb.from('news').update(payload).eq('id',id):sb.from('news').insert(payload));if(error)throw error;toast('تم نشر المحتوى');close();await loadAll(true)}catch(e){toast('تعذر حفظ المنشور: '+e.message,false)}}
  async function deleteNews(id){if(!confirmDelete('هذا المنشور'))return;const {error}=await sb.from('news').delete().eq('id',id);if(error)return toast('تعذر حذف المنشور',false);toast('تم حذف المنشور');await loadAll(true)}

  function renderAwards(){$('awardsList').innerHTML=S.awards.length?S.awards.map(a=>`<div class="item">${img(a.image_url||a.player?.photo_url,a.type)}<div class="meta"><b>${esc(a.type)}</b><small>${esc(a.category)} · ${esc(a.player?.name||'بدون لاعب')}${a.week?` · ${esc(a.week)}`:''}</small></div><div class="actions"><button class="ghost" data-edit-award="${a.id}">تعديل</button><button class="danger" data-delete-award="${a.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد جوائز إدارية مسجلة</div>'}
  function awardForm(id=null){const a=id?byId(S.awards,id):null;show(`<div class="panel-head"><h2>${a?'تعديل الجائزة':'إضافة جائزة'}</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>نوع الجائزة</label><select id="afType">${['أفضل حارس','أفضل لاعب','أفضل لاعب في الأسبوع','رجل المباراة','الهداف','صانع الألعاب'].map(x=>`<option ${a?.type===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>الفئة</label><select id="afCat">${CATS.map(x=>`<option ${a?.category===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>اللاعب</label><select id="afPlayer"><option value="">بدون لاعب</option>${S.players.map(p=>`<option value="${p.id}" ${a?.player_id===p.id?'selected':''}>${esc(p.name)} · ${esc(team(p.team_id)?.name||'')}</option>`).join('')}</select></div><div class="field"><label>الأسبوع</label><input id="afWeek" value="${esc(a?.week||'')}"></div><div class="field"><label>التاريخ</label><input id="afDate" type="date" value="${esc(a?.award_date||'')}"></div></div><div class="field"><label>سبب الاختيار</label><textarea id="afReason">${esc(a?.reason||'')}</textarea></div><div class="uploadbox">${img(a?.image_url,'صورة الجائزة')}<div><label>صورة الجائزة/اللاعب</label><input id="afImage" type="file" accept="image/*"></div></div><div class="savebar"><button id="saveAward" class="primary">حفظ الجائزة</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveAward').onclick=()=>saveAward(a?.id||null)}
  async function saveAward(id){try{let image_url=id?byId(S.awards,id)?.image_url:null;const f=$('afImage').files[0];if(f)image_url=await uploadFile(f,'award',id);const category=val('afCat'),tournament_id=S.tournaments.find(t=>t.division===category)?.id||null;const payload={type:val('afType'),category,tournament_id,player_id:nullable(val('afPlayer')),week:nullable(val('afWeek')),award_date:nullable(val('afDate')),reason:nullable(val('afReason')),image_url};const {error}=await(id?sb.from('awards').update(payload).eq('id',id):sb.from('awards').insert(payload));if(error)throw error;toast('تم حفظ الجائزة');close();await loadAll(true)}catch(e){toast('تعذر حفظ الجائزة: '+e.message,false)}}
  async function deleteAward(id){if(!confirmDelete('هذه الجائزة'))return;const {error}=await sb.from('awards').delete().eq('id',id);if(error)return toast('تعذر حذف الجائزة',false);toast('تم حذف الجائزة');await loadAll(true)}

  function renderSettings(){const s=S.settings||{};$('settingsSummary').innerHTML=`<div class="item">${img(s.logo_url,'شعار البطولة')}<div class="meta"><b>${esc(s.tournament_name||'كأس أغشوركيت 2026')}</b><small>الموسم: ${esc(s.season||'2026')} · الحالة: ${esc(s.tournament_status||'غير محددة')}</small></div><div class="actions"><button class="primary" id="editSettings">تعديل الإعدادات</button></div></div>`;$('editSettings').onclick=settingsForm}
  function settingsForm(){const s=S.settings||{};show(`<div class="panel-head"><h2>إعدادات الموقع</h2><button class="ghost" data-close>إغلاق</button></div><div class="row two"><div class="field"><label>اسم البطولة</label><input id="sfName" value="${esc(s.tournament_name||'')}"></div><div class="field"><label>الموسم</label><input id="sfSeason" value="${esc(s.season||'')}"></div><div class="field"><label>اسم الملعب الافتراضي</label><input id="sfVenue" value="${esc(s.venue_name||'')}"></div><div class="field"><label>حالة البطولة</label><input id="sfStatus" value="${esc(s.tournament_status||'')}"></div><div class="field"><label>رابط واتساب</label><input id="sfWhatsapp" value="${esc(s.contact_whatsapp||'')}"></div><div class="field"><label>رابط فيسبوك</label><input id="sfFacebook" value="${esc(s.contact_facebook||'')}"></div></div><div class="field"><label>العنوان الرئيسي</label><input id="sfHero" value="${esc(s.hero_title||'')}"></div><div class="field"><label>النص الرئيسي</label><textarea id="sfSubtitle">${esc(s.hero_subtitle||'')}</textarea></div><div class="field"><label>معلومات البطولة</label><textarea id="sfInfo">${esc(s.tournament_info||'')}</textarea></div><div class="field"><label>إعلان / تنبيه عام</label><textarea id="sfAnnouncement">${esc(s.announcement||'')}</textarea></div><div class="uploadbox">${img(s.logo_url,'شعار البطولة')}<div><label>شعار البطولة</label><input id="sfLogo" type="file" accept="image/*"></div></div><div class="savebar"><button id="saveSettings" class="primary">حفظ الإعدادات</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveSettings').onclick=saveSettings}
  async function saveSettings(){try{let logo_url=S.settings?.logo_url||'assets/tournament.jpg';const f=$('sfLogo').files[0];if(f)logo_url=await uploadFile(f,'tournament-logo','main');const payload={id:'main',tournament_name:val('sfName')||'كأس أغشوركيت 2026',season:val('sfSeason')||'2026',venue_name:nullable(val('sfVenue')),tournament_status:nullable(val('sfStatus'))||'مستمرة',contact_whatsapp:nullable(val('sfWhatsapp')),contact_facebook:nullable(val('sfFacebook')),hero_title:nullable(val('sfHero')),hero_subtitle:nullable(val('sfSubtitle')),tournament_info:nullable(val('sfInfo')),announcement:nullable(val('sfAnnouncement')),logo_url,updated_at:new Date().toISOString()};const {error}=await sb.from('site_settings').upsert(payload);if(error)throw error;toast('تم تحديث إعدادات الموقع');close();await loadAll(true)}catch(e){toast('تعذر حفظ الإعدادات: '+e.message,false)}}

  function renderMedia(){$('mediaList').innerHTML=S.media.length?S.media.map(m=>`<div class="item">${img(m.public_url,m.caption||m.kind||'صورة')}<div class="meta"><b>${esc(m.caption||m.kind||'صورة')}</b><small>${esc(m.path)}</small></div><div class="actions"><button class="danger" data-delete-media="${m.id}">حذف</button></div></div>`).join(''):'<div class="empty card">لا توجد ملفات مرفوعة من لوحة الإدارة</div>'}
  function mediaForm(){show(`<div class="panel-head"><h2>رفع صورة</h2><button class="ghost" data-close>إغلاق</button></div><div class="field"><label>الصورة</label><input id="medFile" type="file" accept="image/*"></div><div class="field"><label>نوع الصورة</label><select id="medKind"><option value="general">صورة عامة</option><option value="team-logo">شعار فريق</option><option value="player-photo">صورة لاعب</option><option value="news">صورة خبر</option><option value="match">صورة مباراة</option><option value="award">صورة جائزة</option></select></div><div class="field"><label>وصف</label><input id="medCaption"></div><div class="savebar"><button id="saveMedia" class="primary">رفع الصورة</button><button class="ghost" data-close>إلغاء</button></div>`);$('saveMedia').onclick=async()=>{const f=$('medFile').files[0];if(!f)return toast('اختر صورة',false);try{await uploadFile(f,val('medKind')||'general',null,val('medCaption'));toast('تم رفع الصورة');close();await loadAll(true)}catch(e){toast('تعذر رفع الصورة: '+e.message,false)}}}
  async function uploadFile(file,kind='general',entityId=null,caption=null){if(!file?.type?.startsWith('image/'))throw new Error('الملف يجب أن يكون صورة');if(file.size>8*1024*1024)throw new Error('حجم الصورة أكبر من 8MB');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`${kind}/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(cfg.mediaBucket).upload(path,file,{upsert:false,contentType:file.type,cacheControl:'3600'});if(error)throw error;const public_url=sb.storage.from(cfg.mediaBucket).getPublicUrl(path).data.publicUrl;const {error:dbError}=await sb.from('media_assets').insert({bucket:cfg.mediaBucket,path,public_url,kind,entity_id:entityId||null,caption:caption||null});if(dbError)throw dbError;return public_url}
  async function deleteMedia(id){const m=byId(S.media,id);if(!confirmDelete('هذه الصورة من التخزين'))return;const refs=[...S.teams.flatMap(t=>[t.logo_url,t.team_photo_url]),...S.players.map(p=>p.photo_url),...S.news.map(n=>n.image_url),S.settings?.logo_url,...S.awards.map(a=>a.image_url)].filter(Boolean);if(refs.includes(m?.public_url)&&!window.confirm('هذه الصورة مستخدمة حاليًا في الموقع. حذفها سيجعل المرجع مكسورًا. هل تريد المتابعة؟'))return;const {error}=await sb.storage.from(m.bucket||cfg.mediaBucket).remove([m.path]);if(error)return toast('تعذر حذف الملف من التخزين',false);await sb.from('media_assets').delete().eq('id',id);toast('تم حذف الصورة');await loadAll(true)}

  function activateTab(id){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));scrollTo({top:0,behavior:'smooth'})}
  function bindStatic(){
    document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activateTab(b.dataset.tab));
    $('logout').onclick=async()=>{localStorage.removeItem('aghchorguit_admin_link');await sb.auth.signOut();location.replace('login.html')};
    $('teamSearch').oninput=debounce(renderTeams,120);$('teamCategory').onchange=renderTeams;$('playerSearch').oninput=debounce(renderPlayers,120);$('playerCategory').onchange=renderPlayers;$('playerTeamFilter').onchange=renderPlayers;$('matchCategory').onchange=renderMatches;$('matchStatus').onchange=renderMatches;$('eventMatchFilter').onchange=renderEvents;
    if($('addTournament'))$('addTournament').onclick=()=>tournamentForm();$('addTeam').onclick=()=>teamForm();$('addPlayer').onclick=()=>playerForm();$('addMatch').onclick=()=>matchForm();$('addEvent').onclick=()=>eventForm();$('addRef').onclick=()=>refForm();$('addNews').onclick=()=>newsForm();$('addAward').onclick=()=>awardForm();$('addMedia').onclick=mediaForm;
    document.addEventListener('click',e=>{const c=e.target.closest('[data-close]');if(c){close();return}const te=e.target.closest('[data-edit-tournament]');if(te)return tournamentForm(te.dataset.editTournament);const td=e.target.closest('[data-delete-tournament]');if(td)return deleteTournament(td.dataset.deleteTournament);const a=e.target.closest('[data-edit-team]');if(a)return teamForm(a.dataset.editTeam);const b=e.target.closest('[data-delete-team]');if(b)return deleteTeam(b.dataset.deleteTeam);const p=e.target.closest('[data-edit-player]');if(p)return playerForm(p.dataset.editPlayer);const pd=e.target.closest('[data-delete-player]');if(pd)return deletePlayer(pd.dataset.deletePlayer);const ps=e.target.closest('[data-player-events]');if(ps)return playerStatsSheet(ps.dataset.playerEvents);const mf=e.target.closest('[data-edit-match]');if(mf)return matchForm(mf.dataset.editMatch);const md=e.target.closest('[data-delete-match]');if(md)return deleteMatch(md.dataset.deleteMatch);const ms=e.target.closest('[data-start-match]');if(ms)return setMatchStatus(ms.dataset.startMatch,'مباشر');const me=e.target.closest('[data-finish-match]');if(me)return setMatchStatus(me.dataset.finishMatch,'انتهت');const mx=e.target.closest('[data-match-events]');if(mx)return openEventsForMatch(mx.dataset.matchEvents);const ee=e.target.closest('[data-edit-event]');if(ee)return eventForm(ee.dataset.editEvent);const ed=e.target.closest('[data-delete-event]');if(ed)return deleteEvent(ed.dataset.deleteEvent);const rf=e.target.closest('[data-edit-ref]');if(rf)return refForm(rf.dataset.editRef);const rd=e.target.closest('[data-delete-ref]');if(rd)return deleteRef(rd.dataset.deleteRef);const nf=e.target.closest('[data-edit-news]');if(nf)return newsForm(nf.dataset.editNews);const nd=e.target.closest('[data-delete-news]');if(nd)return deleteNews(nd.dataset.deleteNews);const af=e.target.closest('[data-edit-award]');if(af)return awardForm(af.dataset.editAward);const ad=e.target.closest('[data-delete-award]');if(ad)return deleteAward(ad.dataset.deleteAward);const dm=e.target.closest('[data-delete-media]');if(dm)return deleteMedia(dm.dataset.deleteMedia);if(e.target.id==='sheet')close()});
  }
  function subscribe(){if(liveChannel)sb.removeChannel(liveChannel);const reload=debounce(()=>loadAll(true),450);liveChannel=sb.channel('admin-live').on('postgres_changes',{event:'*',schema:'public',table:'tournaments'},reload).on('postgres_changes',{event:'*',schema:'public',table:'teams'},reload).on('postgres_changes',{event:'*',schema:'public',table:'players'},reload).on('postgres_changes',{event:'*',schema:'public',table:'matches'},reload).on('postgres_changes',{event:'*',schema:'public',table:'match_events'},reload).on('postgres_changes',{event:'*',schema:'public',table:'news'},reload).on('postgres_changes',{event:'*',schema:'public',table:'referee_assignments'},reload).on('postgres_changes',{event:'*',schema:'public',table:'awards'},reload).on('postgres_changes',{event:'*',schema:'public',table:'site_settings'},reload).subscribe()}

  (async()=>{if(!await guard())return;bindStatic();await loadAll(true);refreshTeamFilters();renderPlayers();renderEvents();subscribe()})();
})();
