(() => {
  'use strict';
  const cfg=window.AGCH_CONFIG,sb=window.AGCH_ADMIN_SB||window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey,{auth:{persistSession:true,autoRefreshToken:true}});
  const $=id=>document.getElementById(id),esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const show=h=>{$('panel').innerHTML=h;$('sheet').classList.add('on')};
  const close=()=>{$('sheet').classList.remove('on')};
  const notify=(m,ok=true)=>{const t=$('toast');t.textContent=m;t.style.borderColor=ok?'#32634c':'#813c42';t.style.background=ok?'#193d2d':'#431e22';t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2200)};
  async function getMatch(id){const {data,error}=await sb.from('matches').select('*,team_a:teams!matches_team_a_id_fkey(id,name,logo_url),team_b:teams!matches_team_b_id_fkey(id,name,logo_url)').eq('id',id).single();if(error)throw error;return data}
  async function getPlayers(teamId){const {data,error}=await sb.from('players').select('*').eq('team_id',teamId).order('name');if(error)throw error;return data||[]}
  async function getLineups(matchId){const {data,error}=await sb.from('match_lineups').select('*').eq('match_id',matchId);if(error)throw error;const lineups=data||[],ids=lineups.map(x=>x.id);let members=[];if(ids.length){const r=await sb.from('match_lineup_players').select('*').in('lineup_id',ids).order('sort_order');if(r.error)throw r.error;members=r.data||[]}return {lineups,members}}
  function observe(){const root=$('matchList');if(!root)return;const add=()=>root.querySelectorAll('.item').forEach(item=>{const edit=item.querySelector('[data-edit-match]');if(!edit||item.querySelector('[data-lineup-match]'))return;const a=item.querySelector('.actions');if(!a)return;const id=edit.dataset.editMatch;a.insertAdjacentHTML('afterbegin',`<button class="ghost" data-lineup-match="${id}">التشكيلة</button><button class="ghost" data-match-stats="${id}">إحصائيات</button>`)});new MutationObserver(add).observe(root,{childList:true,subtree:true});add()}
  function playerRoleSelect(p,role){return `<select class="lineup-role" data-player="${p.id}"><option value="">خارج القائمة</option><option value="أساسي" ${role==='أساسي'?'selected':''}>أساسي</option><option value="بديل" ${role==='بديل'?'selected':''}>بديل</option></select>`}
  async function openLineup(matchId){try{const m=await getMatch(matchId),[pa,pb,l]=await Promise.all([getPlayers(m.team_a_id),getPlayers(m.team_b_id),getLineups(matchId)]);const section=(t,ps)=>{const lu=l.lineups.find(x=>x.team_id===t.id),mem=new Map(l.members.filter(x=>x.lineup_id===lu?.id).map(x=>[x.player_id,x.role]));return `<div class="card" data-lineup-team="${t.id}" style="margin-top:12px"><h3>${esc(t.name)}</h3><div class="row two"><div class="field"><label>الخطة (اختياري)</label><input class="formation" value="${esc(lu?.formation||'')}" placeholder="4-3-3"></div><div class="field"><label>الحارس</label><select class="goalkeeper"><option value="">غير محدد</option>${ps.map(p=>`<option value="${p.id}" ${lu?.goalkeeper_player_id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>القائد</label><select class="captain"><option value="">غير محدد</option>${ps.map(p=>`<option value="${p.id}" ${lu?.captain_player_id===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div></div><div class="list" style="margin-top:10px">${ps.length?ps.map(p=>`<div class="item"><div class="meta"><b>${esc(p.name)}</b><small>${p.number!=null?'#'+p.number:''}${p.position?' · '+esc(p.position):''}</small></div>${playerRoleSelect(p,mem.get(p.id))}</div>`).join(''):'<div class="empty">لا يوجد لاعبون في هذا الفريق</div>'}</div></div>`};show(`<div class="panel-head"><h2>تشكيلة ${esc(m.team_a.name)} × ${esc(m.team_b.name)}</h2><button class="ghost" data-close-extra>إغلاق</button></div><p class="muted">اختر الأساسيين والاحتياط والحارس والقائد. يمكن ترك الخطة فارغة.</p>${section(m.team_a,pa)}${section(m.team_b,pb)}<div class="savebar"><button id="saveLineupsExtra" class="primary">حفظ التشكيلات</button><button class="ghost" data-close-extra>إلغاء</button></div>`);$('saveLineupsExtra').onclick=()=>saveLineups(matchId)}catch(e){console.error(e);notify('تعذر تحميل التشكيلات: '+e.message,false)}}
  async function saveLineups(matchId){const sections=[...document.querySelectorAll('[data-lineup-team]')];try{for(const sec of sections){const teamId=sec.dataset.lineupTeam,formation=sec.querySelector('.formation').value.trim()||null,goalkeeper=sec.querySelector('.goalkeeper').value||null,captain=sec.querySelector('.captain').value||null;const {data:lu,error}=await sb.from('match_lineups').upsert({match_id:matchId,team_id:teamId,formation,goalkeeper_player_id:goalkeeper,captain_player_id:captain,updated_at:new Date().toISOString()},{onConflict:'match_id,team_id'}).select().single();if(error)throw error;const del=await sb.from('match_lineup_players').delete().eq('lineup_id',lu.id);if(del.error)throw del.error;const members=[...sec.querySelectorAll('.lineup-role')].map((x,i)=>({player_id:x.dataset.player,role:x.value,sort_order:i})).filter(x=>x.role).map(x=>({...x,lineup_id:lu.id}));if(members.length){const ins=await sb.from('match_lineup_players').insert(members);if(ins.error)throw ins.error}}notify('تم حفظ التشكيلات وظهورها في الموقع');close()}catch(e){console.error(e);notify('تعذر حفظ التشكيلات: '+e.message,false)}}
  async function openStats(matchId){try{const m=await getMatch(matchId),{data}=await sb.from('match_stats').select('*').eq('match_id',matchId).maybeSingle(),s=data||{};const fld=(k,label)=>`<div class="field"><label>${esc(label)}</label><div class="row two"><input id="${k}a" type="number" min="0" value="${s[k+'_a']??''}" placeholder="${esc(m.team_a.name)}"><input id="${k}b" type="number" min="0" value="${s[k+'_b']??''}" placeholder="${esc(m.team_b.name)}"></div></div>`;show(`<div class="panel-head"><h2>إحصائيات ${esc(m.team_a.name)} × ${esc(m.team_b.name)}</h2><button class="ghost" data-close-extra>إغلاق</button></div><p class="muted">أدخل فقط الإحصائيات المتوفرة رسميًا. الحقول الفارغة لن تُخترع.</p>${fld('possession','الاستحواذ %')}${fld('shots','التسديدات')}${fld('shots_on_target','على المرمى')}${fld('corners','الركنيات')}${fld('fouls','الأخطاء')}${fld('yellow_cards','البطاقات الصفراء')}${fld('red_cards','البطاقات الحمراء')}<div class="savebar"><button id="saveStatsExtra" class="primary">حفظ الإحصائيات</button><button class="ghost" data-close-extra>إلغاء</button></div>`);$('saveStatsExtra').onclick=()=>saveStats(matchId)}catch(e){console.error(e);notify('تعذر تحميل الإحصائيات',false)}}
  async function saveStats(matchId){const num=id=>{const v=$(id).value.trim();return v===''?null:Number(v)},payload={match_id:matchId,possession_a:num('possessiona'),possession_b:num('possessionb'),shots_a:num('shotsa'),shots_b:num('shotsb'),shots_on_target_a:num('shots_on_targeta'),shots_on_target_b:num('shots_on_targetb'),corners_a:num('cornersa'),corners_b:num('cornersb'),fouls_a:num('foulsa'),fouls_b:num('foulsb'),yellow_cards_a:num('yellow_cardsa'),yellow_cards_b:num('yellow_cardsb'),red_cards_a:num('red_cardsa'),red_cards_b:num('red_cardsb'),updated_at:new Date().toISOString()};const {error}=await sb.from('match_stats').upsert(payload,{onConflict:'match_id'});if(error)return notify('تعذر حفظ الإحصائيات: '+error.message,false);notify('تم حفظ إحصائيات المباراة');close()}
  document.addEventListener('click',e=>{const l=e.target.closest('[data-lineup-match]');if(l){e.preventDefault();e.stopImmediatePropagation();openLineup(l.dataset.lineupMatch);return}const s=e.target.closest('[data-match-stats]');if(s){e.preventDefault();e.stopImmediatePropagation();openStats(s.dataset.matchStats);return}if(e.target.closest('[data-close-extra]')){e.preventDefault();e.stopImmediatePropagation();close()}},true);
  observe();
})();
